#------------------------------------------------------------------------------
# Makefile
#
# Simple makefile for installing the scripts.
#------------------------------------------------------------------------------

all:

install:
	install -d $(PREFIX)/bin
	install -m 775 do_l8_sr.py $(PREFIX)/bin

clean:



