#------------------------------------------------------------------------------
# Makefile
#
# Simple makefile for installing the scripts.
#------------------------------------------------------------------------------

all:

install:
	install -d $(PREFIX)/bin
	install -m 775 surface_reflectance.py $(PREFIX)/bin

clean:

